### ISSUE TITLE
Please explain global constant swift file

### ISSUE THREAD

**Issue by eherson** [tanmayb123/AskTanmay-NLQA-System-#2]
Hi
We know you need to get a user name and password for a Watson Service but it is not clear what services are we using. here are the issues 
From the movie on youtube the ATD is using the Natural Lang. Classifier . Is that correct ?
From the movie on youtube the S-ATD is ALSO using the Natural Lang. Classifier . Is that correct ?

Can we keep the classifier_ID you provided ? because I do not see one provided by Watson 
Also - why do you need the SERSE_GOOGLE_CX for ? CX is for custom search only - and I saw no API key for it

let ATD_CLASSIFIER_ID = "3a84d1x62-nlc-18693"
let ATD_CLASSIFIER_UN = "[ATD Watson UN]"
let ATD_CLASSIFIER_PW = "[ATD Watson PW]"

let SATD_CLASSIFIERS = ["GPE": "3a84d1x62-nlc-20473"]
let SATD_CLASSIFIER_UN = "[SATD Watson UN]"
let SATD_CLASSIFIER_PW = "[SATD Watson PW]"

let SERSE_RESULT_PAGES = 5
let SERSE_GOOGLE_KEY = "[Google CSE API Key]"
let SERSE_GOOGLE_CX = "[Google CSE CX]"

**Comment by tanmayb123** [comment]
Hi - Yes, you are correct about the ATD and S-ATD steps. Unfortunately, you'd have to provide your own ATD and S-ATD Classifier IDs and Credentials. I can help you set that up by providing my training data.
In the email you sent me, you noted that you had converted this to Swift 3. Could you please submit a Pull Request with that Swift 3 updated code when you have a moment? Thanks.
Yes, you'd need a Google Custom Search Engine setup for AskTanmay to work - you'd just need to set the CSE to search the entire web, not just your own website(s).
I can help you set this up - Google does provide $300 free for the CSE and other APIs.

**Comment by eherson** [comment]
Hi
Thank you for your answer
I did find instructions [here ](https://www.ibm.com/watson/developercloud/doc/natural-language-classifier/getting-started.html) how to get the classifier IDs and got it using the cURL command on my sample data.
question: if we are using the Watson Natural Language Classifier service for the ATD and S-ATD then the classifierID for them should be the same. but looking at your constant page provided with the code we can see that in your case, the classifier IDs are not the same. Is that correct ? For me right now the classifierID for ATD and S-ATD are the same (because it is the same service, same user name, same password) 
I saw where I should set the CSE to search but was not able to find anything about the $300 free credit. if you can point me to the correct direction I will set it up.
Will set a Pull Request for you. It is not 3 but 2.3 do you still want it ? My developer advised me that the code for the application you have in the youtube movie is not part of the opensource , was she correct ?
Thank you
eHerson

**Comment by tanmayb123** [comment]
I'll get back to you soon regarding how you can fix this - but for now, I'd recommend pulling in the latest changes. I've just pushed some big changes.

**Comment by eherson** [comment]
Hi Tanmay
CAG part if failing, on the last master version
You can see the attached file for more information,
Can you classify the issue ? is it bug or maybe wrong declaration of the constants ?
Thank you 
[CAG Bug Description.docx](https://github.com/tanmayb123/AskTanmay-NLQA-System-/files/836087/CAG.Bug.Description.docx)

**Comment by eherson** [comment]
Please provide your training data for Natural Language classifier , 
Thank you
